apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80
      nodePort: 30080 
  type: NodePort    # Exposes service only within the cluster

